* I've done more testing of the mv/rm/cp code when operating across filesystems, and things didn't work. Much better now.
* I'm starting to add documentation. I'm using the scripts that come
with the 2.4 kernel sources for generating the docs, since I really
like the way the kernel people do that -- write the docs in DocBook,
but extract comments from the source code. I'm not including those
scripts here -- just looking for them at configure time. If people
don't have 2.4 kernel sources, no problem. They don't need to generate
the docs anyway. I'm playing around with those things for now, so
this is definitely not finished.


git-svn-id: http://svn.enlightenment.org/svn/e/trunk@4861 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33

diff --git a/e17/apps/efsd/configure.in b/e17/apps/efsd/configure.in
--- a/e17/apps/efsd/configure.in
+++ b/e17/apps/efsd/configure.in
@@ -107,6 +107,38 @@ AC_SUBST(edb_cflags)
 AC_SUBST(edb_libs)
 
 
+dnl Look for Linux 2.4.xx sources for sgml documentation scripts.
+AC_MSG_CHECKING("for a Linux 2.4 source tree")
+linux_readme="NONE"
+
+if test -f /usr/src/linux/README; then
+  linux_sources="/usr/src/linux"
+elif test -f /usr/local/src/linux/README; then
+  linux_sources="/usr/local/src/linux"
+fi
+
+if test "x${linux_sources}" != "xNONE"; then
+  head -1 "${linux_sources}/README" | grep 2\.4 > /dev/null;
+  if test $? -eq 0; then
+    AC_MSG_RESULT("yes")
+    DOCGEN="${linux_sources}/scripts/docgen"
+    if test ! -f $DOCGEN; then
+      echo "Docgen script not found, documentation won't be generateable.";
+    fi
+    AC_SUBST(DOCGEN)
+    LINUX_SRC="${linux_sources}"
+    AC_SUBST(LINUX_SRC)
+    toplevel_abs=`pwd`
+    AC_SUBST(toplevel_abs)
+    echo "stealing ${DOCGEN} for manual generation"
+  else
+    AC_MSG_RESULT("no")
+  fi
+else
+  AC_MSG_RESULT("no")
+fi
+
+
 dnl Set PACKAGE_LOCALE_DIR in config.h.
 if test "x${prefix}" = "xNONE"; then
   AC_DEFINE_UNQUOTED(PACKAGE_LOCALE_DIR, "${ac_default_prefix}/${DATADIRNAME}/locale")
@@ -156,6 +188,8 @@ demo/Makefile
 tools/Makefile
 tools/magic2db
 tools/build_pattern_db
+doc/Makefile
+doc/efsd-manual.raw
 ], [
 chmod +x efsd-config
 ])
