Total rewrite of the xml parsing code, now using libxml2 instead. Old functions for parsing is still there, config files still use them. Fix that later or switch to ecore_config.
Also added a new option in the config files since some feeds require a root element for parsing to be done corretly.

Added the e-cvs rss feed (got that one from xcomp)

JFYI: new parsing code is not tested much yet... :-)


git-svn-id: http://svn.enlightenment.org/svn/e/trunk@8408 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33

diff --git a/misc/erss/configure b/misc/erss/configure
--- a/misc/erss/configure
+++ b/misc/erss/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP EDJE_CONFIG edje_libs edje_cflags EDJE_CFLAGS EDJE_LIBS ESMART_CONFIG esmart_libs esmart_cflags ESMART_CFLAGS ESMART_LIBS EWD_CONFIG ewd_libs ewd_cflags EWD_CFLAGS EWD_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP EDJE_CONFIG edje_libs edje_cflags EDJE_CFLAGS EDJE_LIBS ESMART_CONFIG esmart_libs esmart_cflags ESMART_CFLAGS ESMART_LIBS EWD_CONFIG ewd_libs ewd_cflags EWD_CFLAGS EWD_LIBS XML2_CONFIG xml2_libs xml2_cflags XML2_CFLAGS XML2_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -814,6 +814,8 @@ Optional Packages:
   --with-esmart-exec-prefix=PFX Exec prefix where esmart is installed (optional)
   --with-ewd-prefix=PFX       Prefix where ewd is installed (optional)
   --with-ewd-exec-prefix=PFX Exec prefix where ewd is installed (optional)
+  --with-xml2-prefix=PFX       Prefix where xml2 is installed (optional)
+  --with-xml2-exec-prefix=PFX Exec prefix where xml2 is installed (optional)
 
 Some influential environment variables:
   CC          C compiler command
@@ -4175,8 +4177,6 @@ esmart_cflags=`esmart-config --cflags`
 
 
 
-
-
 # Check whether --with-ewd-prefix or --without-ewd-prefix was given.
 if test "${with_ewd_prefix+set}" = set; then
   withval="$with_ewd_prefix"
@@ -4332,6 +4332,167 @@ echo "$as_me: error: Cannot find ewd: Is ewd-config in path?" >&2;}
 
 ewd_libs=`ewd-config --libs`
 ewd_cflags=`ewd-config --cflags`
+
+
+
+
+
+# Check whether --with-xml2-prefix or --without-xml2-prefix was given.
+if test "${with_xml2_prefix+set}" = set; then
+  withval="$with_xml2_prefix"
+  xml2_config_prefix="$withval"
+else
+  xml2_config_prefix=""
+fi;
+
+# Check whether --with-xml2-exec-prefix or --without-xml2-exec-prefix was given.
+if test "${with_xml2_exec_prefix+set}" = set; then
+  withval="$with_xml2_exec_prefix"
+  xml2_config_exec_prefix="$withval"
+else
+  xml2_config_exec_prefix=""
+fi;
+
+  if test x$xml2_config_exec_prefix != x ; then
+     xml2_config_args="$xml2_config_args --exec-prefix=$xml2_config_exec_prefix"
+     if test x${XML2_CONFIG+set} != xset ; then
+       XML2_CONFIG=$xml2_config_exec_prefix/bin/xml2-config
+     fi
+  fi
+  if test x$xml2_config_prefix != x ; then
+     xml2_config_args="$xml2_config_args --prefix=$xml2_config_prefix"
+     if test x${XML2_CONFIG+set} != xset ; then
+       XML2_CONFIG=$xml2_config_prefix/bin/xml2-config
+     fi
+  fi
+
+  # Extract the first word of "xml2-config", so it can be a program name with args.
+set dummy xml2-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XML2_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XML2_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XML2_CONFIG="$XML2_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XML2_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_XML2_CONFIG" && ac_cv_path_XML2_CONFIG="no"
+  ;;
+esac
+fi
+XML2_CONFIG=$ac_cv_path_XML2_CONFIG
+
+if test -n "$XML2_CONFIG"; then
+  echo "$as_me:$LINENO: result: $XML2_CONFIG" >&5
+echo "${ECHO_T}$XML2_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  echo "$as_me:$LINENO: checking for xml2 - version >= 2.6.0" >&5
+echo $ECHO_N "checking for xml2 - version >= 2.6.0... $ECHO_C" >&6
+
+  no_xml2=""
+  if test "$XML2_CONFIG" = "no" ; then
+     no_xml2=yes
+  else
+     XML2_CFLAGS="`$XML2_CONFIG $xml2_config_args --cflags`"
+     XML2_LIBS="`$XML2_CONFIG $xml2_config_args --libs`"
+
+        xml2_config_major_version=`$XML2_CONFIG $xml2_config_args \
+         --version | sed 's/[^0-9]*\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
+        xml2_config_minor_version=`$XML2_CONFIG $xml2_config_args \
+         --version | sed 's/[^0-9]*\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
+        xml2_config_micro_version=`$XML2_CONFIG $xml2_config_args \
+         --version | sed 's/[^0-9]*\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
+        xml2_wanted_major_version="2"
+        xml2_wanted_minor_version="6"
+        xml2_wanted_micro_version="0"
+
+        # Compare wanted version to what config script returned.
+        # If I knew what library was being run, i'd probably also compile
+        # a test program at this point (which also extracted and tested
+        # the version in some library-specific way)
+        if test "$xml2_config_major_version" -lt \
+                        "$xml2_wanted_major_version" \
+          -o \( "$xml2_config_major_version" -eq \
+                        "$xml2_wanted_major_version" \
+            -a "$xml2_config_minor_version" -lt \
+                        "$xml2_wanted_minor_version" \) \
+          -o \( "$xml2_config_major_version" -eq \
+                        "$xml2_wanted_major_version" \
+            -a "$xml2_config_minor_version" -eq \
+                        "$xml2_wanted_minor_version" \
+            -a "$xml2_config_micro_version" -lt \
+                        "$xml2_wanted_micro_version" \) ; then
+          # older version found
+          no_xml2=yes
+          echo -n "*** An old version of xml2 "
+          echo -n "($xml2_config_major_version"
+          echo -n ".$xml2_config_minor_version"
+          echo    ".$xml2_config_micro_version) was found."
+          echo -n "*** You need a version of xml2 newer than "
+          echo -n "$xml2_wanted_major_version"
+          echo -n ".$xml2_wanted_minor_version"
+          echo    ".$xml2_wanted_micro_version."
+          echo "***"
+          echo "*** If you have already installed a sufficiently new version, this error"
+          echo "*** probably means that the wrong copy of the xml2-config shell script is"
+          echo "*** being found. The easiest way to fix this is to remove the old version"
+          echo "*** of xml2, but you can also set the XML2_CONFIG environment to point to the"
+          echo "*** correct copy of xml2-config. (In this case, you will have to"
+          echo "*** modify your LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf"
+          echo "*** so that the correct libraries are found at run-time)"
+        fi
+
+  fi
+  if test "x$no_xml2" = x ; then
+     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+
+  else
+     echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+     if test "$XML2_CONFIG" = "no" ; then
+       echo "*** The xml2-config script installed by xml2 could not be found"
+       echo "*** If xml2 was installed in PREFIX, make sure PREFIX/bin is in"
+       echo "*** your path, or set the XML2_CONFIG environment variable to the"
+       echo "*** full path to xml2-config."
+     fi
+     XML2_CFLAGS=""
+     XML2_LIBS=""
+     { { echo "$as_me:$LINENO: error: Cannot find ewd: Is xml2-config in path?" >&5
+echo "$as_me: error: Cannot find ewd: Is xml2-config in path?" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+
+
+
+xml2_libs=`xml2-config --libs`
+xml2_cflags=`xml2-config --cflags`
+
 
 
 
@@ -4998,6 +5159,11 @@ s,@ewd_libs@,$ewd_libs,;t t
 s,@ewd_cflags@,$ewd_cflags,;t t
 s,@EWD_CFLAGS@,$EWD_CFLAGS,;t t
 s,@EWD_LIBS@,$EWD_LIBS,;t t
+s,@XML2_CONFIG@,$XML2_CONFIG,;t t
+s,@xml2_libs@,$xml2_libs,;t t
+s,@xml2_cflags@,$xml2_cflags,;t t
+s,@XML2_CFLAGS@,$XML2_CFLAGS,;t t
+s,@XML2_LIBS@,$XML2_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
